using System.Collections.Generic;

public class PolishAbilities
{
    public static readonly List<string> abilities = new()
    {
        "Ta karta pojawia siê automatycznie po stronie gracza, który nie zaczyna gry.",
        "Dobierz kartê.",
        "Dobierz 2 karty.",
        "Dobierz tyle kart, aby mieæ ich przynajmniej 5.",
        "Dobierz kartê. Odnowienie 4.",
        "Zagraj wybran¹ kartê ze swojej talii.",
        "Poka¿ 3 losowe karty ze swojej talii. Zagraj jedn¹ z nich.",
        "Poka¿ 3 losowe karty. Stwórz i zagraj jedn¹ z nich.",
        "Cofnij swoj¹ kartê na rêkê i natychmiast zagraj j¹ ponownie.",
        "Wybierz kartê ze sto³u, i zagraj jej kopiê ze swojej talii.",
        "Wybierz kartê ze sto³u, stwórz i zagraj jej bazow¹ kopiê.",
        "Dobierz 3 karty. Wtasuj 3 karty z powrotem do swojej talii.",
        "Dobierz 3 karty. Odrzuæ 3 karty z rêki na cmentarz.",
        "Wtasuj do 3 kart ze swojego cmentarza do swojej talii.",
        "Za ka¿dym razem gdy dobierasz kartê, w inny sposób ni¿ na pocz¹tku tury, wzmocnij mnie o 1.",
        "Jeœli masz wiêcej ni¿ 5 kart na rêce, wzmocnij mnie o 2 za ka¿d¹ nadmiarow¹ kartê.",
        "Mo¿esz zagraæ 2 dodatkowe karty.",
        "Kiedy wymienisz lub odrzucisz mnie z rêki, przyzwij mnie do losowego rzêdu.",
        "Rz¹d 1: Zwiêksz hp obydwóch graczy o 10. Rz¹d 2: Wzmocnij mnie o 5. Rz¹d 3: Zmniejsz hp obydwóch graczy o 10.",
        "Wybierz jedno: Stwórz i zagraj Ice Giant. Stwórz i zagraj Great Golem. Stwórz i zagraj Elder Samurai.",
        "Wybierz jedno: Wzmocnij mnie o 8. Wzmocnij mnie o losow¹ wartoœæ od 0 do 18.",
        "Jeœli w twojej talii startowej nie ma duplikatów, wzmocnij mnie o 1 za ka¿d¹ kartê w twojej talii startowej.",
        "Jeœli w twojej talii startowej nie ma ¿adnej karty w wiêcej ni¿ 2 kopiach, wzmocnij mnie o 1 za ka¿de 2 karty w twojej talii startowej.",
        "Wzmocnij mnie o 2. Odnowienie 1. OpóŸnienie 7: Od teraz zamiast wzmacniaæ, zadawaj mi 1 obra¿eñ.",
        "brak",
        "Zagraj jeszcze jedn¹ kartê.",
        "Odrzuæ wybran¹ kartê z rêki.",
        "Zmniejsz hp obydwóch graczy o 6.",
        "Zadaj mi 1 obra¿eñ. Odnowienie 1.",
        "Wzmocnij mnie o 1. Odnowienie 1. Jeœli jest tura 14 lub póŸniejsza, zniszcz wszystkie swoje karty.",
        "Odrzuæ dowoln¹ liczba kart. Wzmocnij mnie o 3 za ka¿d¹.",
        "Zadaj mi obra¿enia równe numerowi tury.",
        "Zadaj karcie 12 obra¿eñ. Obra¿enia zmniejszaj¹ siê o 1 co turê.",
        "Zadaj mi obra¿enia równe liczbie kart pozosta³ych w twojej talii.",
        "Poka¿ 2 losowe karty ze swojej talii i zagraj jedn¹ z nich.",
        "Zagraj losow¹ kartê ze swojej talii.",
        "Przeciwnik dobiera kartê.",
        "Jeœli na pocz¹tku Twojej tury znajdujê siê w talii lub w rêce, przyzwij jedn¹ losow¹ moj¹ kopiê.",
        "Wzmocnij mnie o 1 za ka¿de 6 twojego hp.",
        "Wzmocnij mnie o 1. Odnowienie 2",
        "Wzmocnij mnie o 1. Odnowienie 1",
        "Wzmocnij mnie o 3. Odnowienie 2",
        "Wzmocnij mnie o numer rundy.",
        "OpóŸnienie 4: Wzmocnij mnie o 8.",
        "OpóŸnienie 4: Wzmocnij mnie o 16.",
        "OpóŸnienie 18: Wzmocnij mnie o 99. Nietykalnoœæ.",
        "Daj karcie 7 pancerza.",
        "Daj karcie 16 pancerza.",
        "Daj karcie 27 pancerza.",
        "Daj karcie w rêce 6 pancerza.",
        "Za ka¿dym razem, gdy zagrasz kartê na prawo ode mnie, przeka¿ jej moje wzmocnienie i pancerz, po czym os³ab mnie o 2.",
        "Odbieram wszystkie obra¿enia skierowane na twoje karty w tym rzêdzie.",
        "Jeœli jest runda 12 lub póŸniejsza, wzmocnij mnie o 7.",
        "Zadaj karcie obra¿enia w wysokoœci aktualnej tury.",
        "Wzmocnij mnie o 1 za ka¿de 2 karty w twojej talii.",
        "Wzmocnij mnie o 1 za ka¿de 6 hp twojego przeciwnika.",
        "Zwiêksz hp obydwóch graczy o 6.",
        "Przenieœ 2 karty do innego rzêdu.",
        "Przenieœ 4 karty do innego rzêdu.",
        "Przenieœ wszystkie inne karty z tego rzêdu do innych rzêdów.",
        "Przenieœ wszystkie karty z przeciwnego rzêdu do innych rzêdów.",
        "Wzmocnij wszystkie inne karty w tym rzêdzie o 1.",
        "Zadaj 2 obra¿enia wszystkim kartom w przeciwnym rzêdzie.",
        "Gdy karta pojawi siê w tym rzêdzie, wzmocnij j¹ o 1.",
        "Gdy karta pojawi siê w tym rzêdzie, daj jej 3 pancerza.",
        "Gdy karta pojawi siê w przeciwnym rzêdzie zadaj jej 2 obra¿enia.",
        "Wzmocnij wszystkie karty w tym rzêdzie o 1. Odnowienie 3.",
        "Zadaj 1 obra¿eñ wszystkim kartom w przeciwnym rzêdzie. Odnowienie 3.",
        "Zadaj 1 obra¿eñ wszystkim kartom w tym rzêdzie. Odnowienie 2.",
        "Przenieœ mnie do nastêpnego rzêdu i wzmocnij wszystkie inne karty w tym rzêdzie o 1. Odnowienie 3.",
        "Przenieœ mnie do nastêpnego rzêdu i zadaj 1 obra¿eñ wszystkim kartom w przeciwnym rzêdzie. Odnowienie 3.",
        "Wzmocnij kartê i s¹siaduj¹ce z ni¹ karty o 4.",
        "Zadaj karcie i s¹siaduj¹cym z ni¹ kartom 4 obra¿enia.",
        "Wybierz jedno: Wzmocnij wszystkie inne karty w tym rzêdzie o 1. Zadaj 1 obra¿eñ wszystkim kartom w przeciwnym rzêdzie.",
        "Zniszcz wszystkie inne karty w tym rzêdzie. Nietykalnoœæ.",
        "Ustaw si³ê wszystkich innych kart w tym rzêdzie na 5.",
        "Za ka¿dym razem gdy twoja karta siê poruszy wzmocnij j¹ o 1.",
        "Za ka¿dym razem gdy karta przeciwnika siê poruszy zadaj jej 1 obra¿eñ.",
        "Za ka¿dym razem gdy twoja karta siê poruszy wzmocnij j¹ o 1. Za ka¿dym razem gdy karta przeciwnika siê poruszy zadaj jej 1 obra¿eñ.",
        "Wzmocnij mnie o numer tury. Zmniejsz wzmocnienie o 1 za ka¿d¹ inn¹ kartê moim rzêdzie.",
        "Zadaj karcia obra¿enia równe numerowi tury. Zmniejsza obra¿enia o 1 za ka¿d¹ inn¹ kartê w jej rzêdzie.",
        "Wzmocnij mnie o 1 za ka¿d¹ inn¹ kartê w tym rzêdzie.",
        "Zadaj karcie obra¿enia równe dwukrotnoœci kart w jej rzêdzie.",
        "Kiedy w tym rzêdzie pojawi siê karta, zadaj mi 2 obra¿enia. Odwet: Zadaj 4 obra¿eñ. wszystkim katrom w tym rzêdzie.",
        "Zadaj 1 obra¿eñ wszystkim kartom w przeciwnym rzêdzie. Jeœli którakolwiek z nich zginie, powtórz tê umiejêtnoœæ.",
        "Zawsze gdy karta pojawia siê po twojej stronie, wzmocnij mnie o 1.",
        "Zawsze gdy karta pojawia siê po twojej stronie, wzmocnij j¹ o 1.",
        "Wzmocnij wszystkie swoje karty na stole o 1.",
        "Wzmocnij wszystkie karty na stole o 2.",
        "Ulepsz o 1 wszystkie inne swoje jednostki, które nie s¹ szpiegami, gdziekolwiek siê znajduj¹.",
        "Wzmocnij wszystkie najs³absze karty po twojej stronie o 1. Powtórz ³¹cznie 2 razy.",
        "Wzmocnij wszystkie swoje najs³absze karty o 1. Odnowienie 3.",
        "Wzmocnij kartê i wszystkie karty o tej samej sile po tej samej stronie stronie o 2.",
        "Wzmocnij kartê i wszystkie jej kopie po tej samej stronie o 3.",
        "Za ka¿dym razem gdy w moim rzêdzie pojawi siê karta, której si³a wynosi mniej ni¿ 5, ustaw jej si³ê na 5.",
        "Stwórz moj¹ bazow¹ kopie.",
        "Przyzwij 2 moje kopie ze swojej talii.",
        "OpóŸnienie 2: Przyzwij moj¹ kopie ze swojej talii.",
        "Wzmocnij ka¿d¹ inn¹ Watahê po twojej stronie o 4.",
        "Wzmocnij mnie o 0. Wzmocnienie zwiêksza siê o 3 ka¿dego NiedŸwiedzia zagranego przez ciebie w tej grze.",
        "Wybierz kartê i stwórz jej kopiê w swojej talii.",
        "Wybierz kartê i stwórz 2 jej kopie w swojej talii.",
        "Wtasuj wybran¹ kartê ze swojego cmentarza do talii wraz ze wszystkimi jej kopiami.",
        "Odwet: Utwórz Pisklê w tym rzêdzie.",
        "brak",
        "Stwórz i zagraj jeszcze jedn¹ Larvê. Odwet: Utwórz Robaki w tym rzêdzie.",
        "brak",
        "Odwet: Stwórz Jad w swojej rêce.",
        "Zadaj karcie 7 obra¿eñ. Zagraj jeszcze jedn¹ kartê.",
        "Odwet: Stwórz Olbrzymi¹tko w swojej rêce.",
        "brak",
        "Odwet: Wskrzeœ mnie bez umiejêtnoœci.",
        "Odwet: Zmniejsz moj¹ si³ê bazow¹ o po³owê i wskrzeœ mnie.",
        "Zadaj najsilniejszej karcie przeciwnika 1 obra¿eñ. Odnowienie 1. Odwet: Zadaj najsilniejszej karcie przeciwnika 6 obra¿eñ.",
        "Odwet: Wezwij moj¹ kopiê ze swojej talii.",
        "Wskrzeœ wszystkie moje kopie z twojego cmentarza.",
        "Zniszcz kartê z prawej i z lewej i wzmocnij mnie o ich si³ê.",
        "Zniszcz wszystkie inne karty w tym rzêdzie i wzmocnij mnie o ich si³ê.",
        "Zniszcz kartê z mojej prawej i wzmocnij mnie o jej si³ê. Odnowienie 3.",
        "Zniszcz swoj¹ kartê i zadaj obra¿enia równe jej sile wybranej karcie.",
        "Wybierz swoj¹ kartê i wzmocnij mnie o jej si³ê bazow¹ pomniejszon¹ o 10.",
        "Wybierz jedno: Zniszcz kartê z prawej i z lewej i wzmocnij mnie o ich si³ê. Zadaj mi 4 obra¿eñ, po czym stwórz i zagraj jedn¹ Larwê.",
        "Zniszcz wszystkie inne karty. Nietykalnoœæ.",
        "Za ka¿dym razem gdy twoja karta zginie, stwórz w jej rzêdzie paj¹czka.",
        "brak",
        "Ulepsz mnie o 3.",
        "Ulepsz kartê o 4.",
        "Ulepsz 2 karty o 3.",
        "Wskrzeœ kartê ze swojego cmentarza.",
        "Odrzuæ do 3 kart ze swojej talii.",
        "Ustaw si³ê bazow¹ karty na jej aktualn¹ si³ê.",
        "Odrzuæ kartê, która nie jest szpiegiem, ze swojej rêki i wzmocnij mnie o po³owê jej si³y.",
        "Wygnaj kartê, która nie jest szpiegiem, ze swojego cmentarza i wzmocnij mnie o po³owê jej si³y.",
        "Wygnaj do 10 jednostek ze swojego cmentarza i wzmocnij mnie o 2 za ka¿d¹ z nich.",
        "Zadaj 2 obra¿enia wszystkim innym kartom na stole.",
        "Zadaj karcie 4 obra¿enia.",
        "Zadaj karcie 6 obra¿enia.",
        "Zadaj karcie 8 obra¿eñ.",
        "Zadaj karcie 10 obra¿eñ.",
        "Zadaj karcie 13 obra¿eñ.",
        "Zadaj karcie 7 obra¿eñ. Wzmocnij mnie za nadmierne obra¿enia.",
        "Zadaj karcie 4 obra¿eñ. Jeœli zostanie zabita wzmocnij mnie o 6.",
        "Zadaj karcie 5 obra¿eñ. Jeœli prze¿yje wzmocnij mnie o 5.",
        "Zadaj 1 obra¿eñ 4 razy.",
        "Zadaj 3 obra¿enia 2 wrogom.",
        "Zadaj 3 obra¿enia wybranej karcie i wszystkim karom o tej samej sile po tej samej stronie.",
        "Zadaj karcie i wszystkim jej kopi¹ po tej samej stronie 3 obra¿enia.",
        "Zmniejsz si³ê wybranej karty o po³owê.",
        "Zresetuj si³ê karty do si³y bazowej.",
        "Ustaw si³ê karty na 11.",
        "Zablokuj kartê.",
        "Zamieñ si³ê dwóch kart.",
        "Przenieœ wybran¹ kartê o sile 5 lub mniejszej do przeciwnego rzêdu.",
        "Wybierz kartê i wzmocnij mnie o pó³torej jej si³y. Cofnij j¹ na swoj¹ rêkê i zagraj ponowanie j¹. Nietykalnoœæ.",
        "Zniszcz kartê.",
        "Zniszcz kartê, która nie jest wzmocniona.",
        "Zniszcz kartê, która jest jest zraniona.",
        "Zniszcz wszystkie inne najsilniejsze karty.",
        "Zniszcz wszystkie najs³absze karty.",
        "Zniszcz wszystkie ranne karty przeciwnika.",
        "Zawsze gdy karta pojawi siê po stronie przeciwnika zadaj jej 1 obra¿eñ.",
        "Zadaj najsilniejszej karcie przeciwnika 1 obra¿eñ. Odnowienie 1.",
        "Zadaj wszystkim najsilniejszym kartom przeciwnika 1 obra¿eñ. Powtórz ³¹cznie 3 razy.",
        "Zadaj wszystkim najsilniejszym kartom przeciwnika 1 obra¿eñ. Odnowienie 3.",
        "Zadaj 1 obra¿eñ wszystkim kartom przeciwnika.",
        "Odwet: Zadaj wszystkim jednostkom w tym rzêdzie 6 obra¿eñ.",
        "Zadaj 2 obra¿enia wszystkim rannym kartom przeciwnika.",
        "Za ka¿dym razem, gdy karta w przeciwnym rzêdzie zostanie zraniona, wzmocnij mnie o 1",
        "Za ka¿dym razem gdy karta przeciwnika zostaje zabita wzmocnij mnie o 2.",
        "Wzmocnij mnie o 2 za ka¿d¹ ranna kartê przeciwnika.",
        "Wzmocnij mnie o numer aktualnej rundy. Zadaj mi 1 obra¿eñ za ka¿d¹ kartê na stole przeciwnika.",
        "Stwórz po stronie przeciwnika Mistycznego Golema.",
        "Odwet: Wzmocnij najs³abszego Zabójcê Golemów po przeciwnej stronie o 15.",
        "Wzmocnij kartê o 6.",
        "Wzmocnij kartê o 11.",
        "Wzmocnij kartê o 16.",
        "Zwiêksz si³ê wybranej karty o 1/4.",
        "Wzmocnij kartê o 1 4 razy.",
        "Wzmocnij 2 karty o 5.",
        "Wzmocnij kartê w rêce o 4.",
        "Przenieœ ca³e wzmocnienie z jednej swojej karty na inn¹.",
        "Zamieñ si³ê dwóch swoich kart.",
        "Wzmocnij wszystkie swoje wzmocnione karty o 1.",
        "Wzmocnij swoj¹ najs³absz¹ kartê o 1. Odnowienie 1",
        "Wzmocnij kartê z prawej o 1. Odnowienie 1.",
        "Wzmocnij mnie o 1 za ka¿d¹ wzmocnion¹ kartê po twojej stronie.",
        "Za ka¿dym razem, gdy otrzymujê wzmocnienie, zadaj najsilniejszemu wrogowi 1 obra¿eñ.",
        "Kiedy stajê siê wzmocniony, zadaj najsilniejszej kracie przeciwnika 10 obra¿eñ.",
        "Kiedy stajê siê wzmocniony, zadaj najsilniejszej kracie przeciwnika obra¿enia równe wartoœci mojego wzmocnienia.",
        "Kiedy po raz pierwszy moja si³a wyniesie 30 lub wiêcej, zadaj najsilniejszej kracie przeciwnika 9 obra¿eñ.",
        "OpóŸnienie 4: Zwiêksz moj¹ si³ê o po³owê.",
        "Zniszcz wszystkie karty, które nie s¹ wzmocnione. Nietykalnoœæ."
    };
}